AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  event-manager-app

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON

Resources:
  # This is our explicitly defined HTTP API
  EventsApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
        AllowMethods:
          - GET
          - POST
          - OPTIONS

  EventsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: EventsManagementTable
      PrimaryKey:
        Name: PK
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # All functions now have an "Api" event source that points to the explicit API above
  CreateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/create_event/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 20
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /events
            Method: post
            ApiId: !Ref EventsApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref EventsTable

  RegisterParticipantFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/register_participant/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 20
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /events/{event_id}/participants
            Method: post
            ApiId: !Ref EventsApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref EventsTable

  GetParticipantsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/get_participants/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 20
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /events/{event_id}/participants
            Method: get
            ApiId: !Ref EventsApi
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref EventsTable

Outputs:
  EventsApiUrl:
    Description: "API Gateway endpoint URL for Events API"
    Value: !Sub "https://${EventsApi}.execute-api.${AWS::Region}.amazonaws.com"