AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  event-manager-app

  Sample SAM Template for event-manager-app

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON


Resources:
  EventsApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowCredentials: true

  EventsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: EventsManagementTable
      PrimaryKey:
        Name: PK
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  CreateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/create_event/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 20
      Architectures:
        - x86_64
      Events:
        CreateEventApi:
          Type: HttpApi
          Properties:
            Path: /events
            Method: POST
            ApiId: !Ref EventsApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref EventsTable

  RegisterParticipantFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/register_participant/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 20
      Architectures:
        - x86_64
      Events:
        RegisterParticipantApi:
          Type: HttpApi
          Properties:
            Path: /events/{eventId}/participants
            Method: POST
            ApiId: !Ref EventsApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref EventsTable
  
  GetParticipantsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/get_participants/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 20
      Architectures:
        - x86_64
      Events:
        GetParticipantsApi:
          Type: HttpApi
          Properties:
            Path: /events/{eventId}/participants
            Method: GET
            ApiId: !Ref EventsApi
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref EventsTable

Outputs:
  EventsApi:
    Description: "API Gateway endpoint URL for Events API"
    Value: !Sub "https://${EventsApi}.execute-api.${AWS::Region}.amazonaws.com/"
  CreateEventFunctionArn:
    Description: "Create Event Lambda Function ARN"
    Value: !GetAtt CreateEventFunction.Arn
  CreateEventFunctionIamRoleArn:
    Description: "Implicit IAM Role created for Create Event function"
    Value: !GetAtt CreateEventFunctionRole.Arn