name: Deploy AWS SAM Application

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches:
      - main

# These permissions are needed for the OIDC connection
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1 # Change this to your AWS region if different

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Change this to match your template.yaml runtime

      - name: Build SAM Application
        run: sam build

      - name: Deploy SAM Application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --no-progressbar --capabilities CAPABILITY_IAM